/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = clipapisdk.Client.OpenAPIDateConverter;

namespace clipapisdk.Model
{
    /// <summary>
    /// DeviceGetAllOfMetadata
    /// </summary>
    [DataContract(Name = "DeviceGet_allOf_metadata")]
    public partial class DeviceGetAllOfMetadata : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Archetype
        /// </summary>
        [DataMember(Name = "archetype", EmitDefaultValue = false)]
        public ProductArchetype? Archetype { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DeviceGetAllOfMetadata" /> class.
        /// </summary>
        /// <param name="name">Human readable name of a resource.</param>
        /// <param name="archetype">archetype.</param>
        public DeviceGetAllOfMetadata(string name = default(string), ProductArchetype? archetype = default(ProductArchetype?))
        {
            this.Name = name;
            this.Archetype = archetype;
        }

        /// <summary>
        /// Human readable name of a resource
        /// </summary>
        /// <value>Human readable name of a resource</value>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeviceGetAllOfMetadata {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Archetype: ").Append(Archetype).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Name (string) maxLength
            if (this.Name != null && this.Name.Length > 32)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be less than 32.", new [] { "Name" });
            }

            // Name (string) minLength
            if (this.Name != null && this.Name.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Name, length must be greater than 1.", new [] { "Name" });
            }

            yield break;
        }
    }

}
