/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = clipapisdk.Client.OpenAPIDateConverter;

namespace clipapisdk.Model
{
    /// <summary>
    /// Basic feature containing timed effect properties.
    /// </summary>
    [DataContract(Name = "LightGet_allOf_timed_effects")]
    public partial class LightGetAllOfTimedEffects : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Effect
        /// </summary>
        [DataMember(Name = "effect", EmitDefaultValue = false)]
        public SupportedTimedEffects? Effect { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [DataMember(Name = "status", EmitDefaultValue = false)]
        public SupportedTimedEffects? Status { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="LightGetAllOfTimedEffects" /> class.
        /// </summary>
        /// <param name="effect">effect.</param>
        /// <param name="effectValues">Possible timed effect values you can set in a light.</param>
        /// <param name="status">status.</param>
        /// <param name="statusValues">Possible status values in which a light could be when playing a timed effect..</param>
        /// <param name="duration">Duration is mandatory when timed effect is set except for no_effect. Resolution decreases for a larger duration. e.g Effects with duration smaller than a minute will be rounded to a resolution of 1s, while effects with duration larger than an hour will be arounded up to a resolution of 300s. Duration has a max of 21600000 ms..</param>
        public LightGetAllOfTimedEffects(SupportedTimedEffects? effect = default(SupportedTimedEffects?), List<SupportedTimedEffects> effectValues = default(List<SupportedTimedEffects>), SupportedTimedEffects? status = default(SupportedTimedEffects?), List<SupportedTimedEffects> statusValues = default(List<SupportedTimedEffects>), int duration = default(int))
        {
            this.Effect = effect;
            this.EffectValues = effectValues;
            this.Status = status;
            this.StatusValues = statusValues;
            this.Duration = duration;
        }

        /// <summary>
        /// Possible timed effect values you can set in a light
        /// </summary>
        /// <value>Possible timed effect values you can set in a light</value>
        [DataMember(Name = "effect_values", EmitDefaultValue = false)]
        public List<SupportedTimedEffects> EffectValues { get; set; }

        /// <summary>
        /// Possible status values in which a light could be when playing a timed effect.
        /// </summary>
        /// <value>Possible status values in which a light could be when playing a timed effect.</value>
        [DataMember(Name = "status_values", EmitDefaultValue = false)]
        public List<SupportedTimedEffects> StatusValues { get; set; }

        /// <summary>
        /// Duration is mandatory when timed effect is set except for no_effect. Resolution decreases for a larger duration. e.g Effects with duration smaller than a minute will be rounded to a resolution of 1s, while effects with duration larger than an hour will be arounded up to a resolution of 300s. Duration has a max of 21600000 ms.
        /// </summary>
        /// <value>Duration is mandatory when timed effect is set except for no_effect. Resolution decreases for a larger duration. e.g Effects with duration smaller than a minute will be rounded to a resolution of 1s, while effects with duration larger than an hour will be arounded up to a resolution of 300s. Duration has a max of 21600000 ms.</value>
        [DataMember(Name = "duration", EmitDefaultValue = false)]
        public int Duration { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LightGetAllOfTimedEffects {\n");
            sb.Append("  Effect: ").Append(Effect).Append("\n");
            sb.Append("  EffectValues: ").Append(EffectValues).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  StatusValues: ").Append(StatusValues).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
