/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = clipapisdk.Client.OpenAPIDateConverter;

namespace clipapisdk.Model
{
    /// <summary>
    /// MotionGetAllOfMotion
    /// </summary>
    [DataContract(Name = "MotionGet_allOf_motion")]
    public partial class MotionGetAllOfMotion : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MotionGetAllOfMotion" /> class.
        /// </summary>
        /// <param name="motion">Deprecated. Moved to motion_report/motion..</param>
        /// <param name="motionValid">Deprecated. Motion is valid when motion_report property is present, invalid when absent..</param>
        /// <param name="motionReport">motionReport.</param>
        public MotionGetAllOfMotion(bool motion = default(bool), bool motionValid = default(bool), MotionGetAllOfMotionMotionReport motionReport = default(MotionGetAllOfMotionMotionReport))
        {
            this.Motion = motion;
            this.MotionValid = motionValid;
            this.MotionReport = motionReport;
        }

        /// <summary>
        /// Deprecated. Moved to motion_report/motion.
        /// </summary>
        /// <value>Deprecated. Moved to motion_report/motion.</value>
        [DataMember(Name = "motion", EmitDefaultValue = true)]
        public bool Motion { get; set; }

        /// <summary>
        /// Deprecated. Motion is valid when motion_report property is present, invalid when absent.
        /// </summary>
        /// <value>Deprecated. Motion is valid when motion_report property is present, invalid when absent.</value>
        [DataMember(Name = "motion_valid", EmitDefaultValue = true)]
        public bool MotionValid { get; set; }

        /// <summary>
        /// Gets or Sets MotionReport
        /// </summary>
        [DataMember(Name = "motion_report", EmitDefaultValue = false)]
        public MotionGetAllOfMotionMotionReport MotionReport { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MotionGetAllOfMotion {\n");
            sb.Append("  Motion: ").Append(Motion).Append("\n");
            sb.Append("  MotionValid: ").Append(MotionValid).Append("\n");
            sb.Append("  MotionReport: ").Append(MotionReport).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
