/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = clipapisdk.Client.OpenAPIDateConverter;

namespace clipapisdk.Model
{
    /// <summary>
    /// Current status of the lamp with dynamics.
    /// </summary>
    /// <value>Current status of the lamp with dynamics.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SupportedDynamicStatus
    {
        /// <summary>
        /// Enum DynamicPalette for value: dynamic_palette
        /// </summary>
        [EnumMember(Value = "dynamic_palette")]
        DynamicPalette = 1,

        /// <summary>
        /// Enum None for value: none
        /// </summary>
        [EnumMember(Value = "none")]
        None = 2
    }

}
