/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = clipapisdk.Client.OpenAPIDateConverter;

namespace clipapisdk.Model
{
    /// <summary>
    /// Indicates which signal is currently active.
    /// </summary>
    /// <value>Indicates which signal is currently active.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SupportedSignals
    {
        /// <summary>
        /// Enum NoSignal for value: no_signal
        /// </summary>
        [EnumMember(Value = "no_signal")]
        NoSignal = 1,

        /// <summary>
        /// Enum OnOff for value: on_off
        /// </summary>
        [EnumMember(Value = "on_off")]
        OnOff = 2,

        /// <summary>
        /// Enum OnOffColor for value: on_off_color
        /// </summary>
        [EnumMember(Value = "on_off_color")]
        OnOffColor = 3,

        /// <summary>
        /// Enum Alternating for value: alternating
        /// </summary>
        [EnumMember(Value = "alternating")]
        Alternating = 4
    }

}
