/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using clipapisdk.Client;
using clipapisdk.Api;
// uncomment below to import models
//using clipapisdk.Model;

namespace clipapisdk.Test.Api
{
    /// <summary>
    ///  Class for testing DevicePowerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DevicePowerApiTests : IDisposable
    {
        private DevicePowerApi instance;

        public DevicePowerApiTests()
        {
            instance = new DevicePowerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DevicePowerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DevicePowerApi
            //Assert.IsType<DevicePowerApi>(instance);
        }

        /// <summary>
        /// Test GetDevicePower
        /// </summary>
        [Fact]
        public void GetDevicePowerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string deviceId = null;
            //var response = instance.GetDevicePower(deviceId);
            //Assert.IsType<GetDevicePowers200Response>(response);
        }

        /// <summary>
        /// Test GetDevicePowers
        /// </summary>
        [Fact]
        public void GetDevicePowersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetDevicePowers();
            //Assert.IsType<GetDevicePowers200Response>(response);
        }
    }
}
