/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing AuthenticateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuthenticateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuthenticateRequest
        //private AuthenticateRequest instance;

        public AuthenticateRequestTests()
        {
            // TODO uncomment below to create an instance of AuthenticateRequest
            //instance = new AuthenticateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuthenticateRequest
        /// </summary>
        [Fact]
        public void AuthenticateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuthenticateRequest
            //Assert.IsType<AuthenticateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Devicetype'
        /// </summary>
        [Fact]
        public void DevicetypeTest()
        {
            // TODO unit test for the property 'Devicetype'
        }

        /// <summary>
        /// Test the property 'Generateclientkey'
        /// </summary>
        [Fact]
        public void GenerateclientkeyTest()
        {
            // TODO unit test for the property 'Generateclientkey'
        }
    }
}
