/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing Color
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ColorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Color
        //private Color instance;

        public ColorTests()
        {
            // TODO uncomment below to create an instance of Color
            //instance = new Color();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Color
        /// </summary>
        [Fact]
        public void ColorInstanceTest()
        {
            // TODO uncomment below to test "IsType" Color
            //Assert.IsType<Color>(instance);
        }

        /// <summary>
        /// Test the property 'Xy'
        /// </summary>
        [Fact]
        public void XyTest()
        {
            // TODO unit test for the property 'Xy'
        }
    }
}
