/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing ColorTemperaturePalettePostColorTemperature
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ColorTemperaturePalettePostColorTemperatureTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ColorTemperaturePalettePostColorTemperature
        //private ColorTemperaturePalettePostColorTemperature instance;

        public ColorTemperaturePalettePostColorTemperatureTests()
        {
            // TODO uncomment below to create an instance of ColorTemperaturePalettePostColorTemperature
            //instance = new ColorTemperaturePalettePostColorTemperature();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ColorTemperaturePalettePostColorTemperature
        /// </summary>
        [Fact]
        public void ColorTemperaturePalettePostColorTemperatureInstanceTest()
        {
            // TODO uncomment below to test "IsType" ColorTemperaturePalettePostColorTemperature
            //Assert.IsType<ColorTemperaturePalettePostColorTemperature>(instance);
        }

        /// <summary>
        /// Test the property 'Mirek'
        /// </summary>
        [Fact]
        public void MirekTest()
        {
            // TODO unit test for the property 'Mirek'
        }
    }
}
