/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing DevicePowerGetAllOfPowerState
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DevicePowerGetAllOfPowerStateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DevicePowerGetAllOfPowerState
        //private DevicePowerGetAllOfPowerState instance;

        public DevicePowerGetAllOfPowerStateTests()
        {
            // TODO uncomment below to create an instance of DevicePowerGetAllOfPowerState
            //instance = new DevicePowerGetAllOfPowerState();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DevicePowerGetAllOfPowerState
        /// </summary>
        [Fact]
        public void DevicePowerGetAllOfPowerStateInstanceTest()
        {
            // TODO uncomment below to test "IsType" DevicePowerGetAllOfPowerState
            //Assert.IsType<DevicePowerGetAllOfPowerState>(instance);
        }

        /// <summary>
        /// Test the property 'BatteryState'
        /// </summary>
        [Fact]
        public void BatteryStateTest()
        {
            // TODO unit test for the property 'BatteryState'
        }

        /// <summary>
        /// Test the property 'BatteryLevel'
        /// </summary>
        [Fact]
        public void BatteryLevelTest()
        {
            // TODO unit test for the property 'BatteryLevel'
        }
    }
}
