/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing DimmingDelta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DimmingDeltaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DimmingDelta
        //private DimmingDelta instance;

        public DimmingDeltaTests()
        {
            // TODO uncomment below to create an instance of DimmingDelta
            //instance = new DimmingDelta();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DimmingDelta
        /// </summary>
        [Fact]
        public void DimmingDeltaInstanceTest()
        {
            // TODO uncomment below to test "IsType" DimmingDelta
            //Assert.IsType<DimmingDelta>(instance);
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }

        /// <summary>
        /// Test the property 'BrightnessDelta'
        /// </summary>
        [Fact]
        public void BrightnessDeltaTest()
        {
            // TODO unit test for the property 'BrightnessDelta'
        }
    }
}
