/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing Dimming
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DimmingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Dimming
        //private Dimming instance;

        public DimmingTests()
        {
            // TODO uncomment below to create an instance of Dimming
            //instance = new Dimming();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Dimming
        /// </summary>
        [Fact]
        public void DimmingInstanceTest()
        {
            // TODO uncomment below to test "IsType" Dimming
            //Assert.IsType<Dimming>(instance);
        }

        /// <summary>
        /// Test the property 'Brightness'
        /// </summary>
        [Fact]
        public void BrightnessTest()
        {
            // TODO unit test for the property 'Brightness'
        }
    }
}
