/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing Dynamics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DynamicsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Dynamics
        //private Dynamics instance;

        public DynamicsTests()
        {
            // TODO uncomment below to create an instance of Dynamics
            //instance = new Dynamics();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Dynamics
        /// </summary>
        [Fact]
        public void DynamicsInstanceTest()
        {
            // TODO uncomment below to test "IsType" Dynamics
            //Assert.IsType<Dynamics>(instance);
        }

        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

        /// <summary>
        /// Test the property 'Speed'
        /// </summary>
        [Fact]
        public void SpeedTest()
        {
            // TODO unit test for the property 'Speed'
        }
    }
}
