/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing GroupedLightGetAllOfAlert
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupedLightGetAllOfAlertTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GroupedLightGetAllOfAlert
        //private GroupedLightGetAllOfAlert instance;

        public GroupedLightGetAllOfAlertTests()
        {
            // TODO uncomment below to create an instance of GroupedLightGetAllOfAlert
            //instance = new GroupedLightGetAllOfAlert();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroupedLightGetAllOfAlert
        /// </summary>
        [Fact]
        public void GroupedLightGetAllOfAlertInstanceTest()
        {
            // TODO uncomment below to test "IsType" GroupedLightGetAllOfAlert
            //Assert.IsType<GroupedLightGetAllOfAlert>(instance);
        }

        /// <summary>
        /// Test the property 'ActionValues'
        /// </summary>
        [Fact]
        public void ActionValuesTest()
        {
            // TODO unit test for the property 'ActionValues'
        }
    }
}
