/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing LightGetAllOfPowerup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LightGetAllOfPowerupTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LightGetAllOfPowerup
        //private LightGetAllOfPowerup instance;

        public LightGetAllOfPowerupTests()
        {
            // TODO uncomment below to create an instance of LightGetAllOfPowerup
            //instance = new LightGetAllOfPowerup();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LightGetAllOfPowerup
        /// </summary>
        [Fact]
        public void LightGetAllOfPowerupInstanceTest()
        {
            // TODO uncomment below to test "IsType" LightGetAllOfPowerup
            //Assert.IsType<LightGetAllOfPowerup>(instance);
        }

        /// <summary>
        /// Test the property 'Preset'
        /// </summary>
        [Fact]
        public void PresetTest()
        {
            // TODO unit test for the property 'Preset'
        }

        /// <summary>
        /// Test the property 'Configured'
        /// </summary>
        [Fact]
        public void ConfiguredTest()
        {
            // TODO unit test for the property 'Configured'
        }

        /// <summary>
        /// Test the property 'On'
        /// </summary>
        [Fact]
        public void OnTest()
        {
            // TODO unit test for the property 'On'
        }

        /// <summary>
        /// Test the property 'Dimming'
        /// </summary>
        [Fact]
        public void DimmingTest()
        {
            // TODO unit test for the property 'Dimming'
        }
    }
}
