/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing LightGetAllOfPowerupDimming
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LightGetAllOfPowerupDimmingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LightGetAllOfPowerupDimming
        //private LightGetAllOfPowerupDimming instance;

        public LightGetAllOfPowerupDimmingTests()
        {
            // TODO uncomment below to create an instance of LightGetAllOfPowerupDimming
            //instance = new LightGetAllOfPowerupDimming();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LightGetAllOfPowerupDimming
        /// </summary>
        [Fact]
        public void LightGetAllOfPowerupDimmingInstanceTest()
        {
            // TODO uncomment below to test "IsType" LightGetAllOfPowerupDimming
            //Assert.IsType<LightGetAllOfPowerupDimming>(instance);
        }

        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }

        /// <summary>
        /// Test the property 'Dimming'
        /// </summary>
        [Fact]
        public void DimmingTest()
        {
            // TODO unit test for the property 'Dimming'
        }

        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
    }
}
