/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing LightLevelGetAllOfLightLightLevelReport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LightLevelGetAllOfLightLightLevelReportTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LightLevelGetAllOfLightLightLevelReport
        //private LightLevelGetAllOfLightLightLevelReport instance;

        public LightLevelGetAllOfLightLightLevelReportTests()
        {
            // TODO uncomment below to create an instance of LightLevelGetAllOfLightLightLevelReport
            //instance = new LightLevelGetAllOfLightLightLevelReport();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LightLevelGetAllOfLightLightLevelReport
        /// </summary>
        [Fact]
        public void LightLevelGetAllOfLightLightLevelReportInstanceTest()
        {
            // TODO uncomment below to test "IsType" LightLevelGetAllOfLightLightLevelReport
            //Assert.IsType<LightLevelGetAllOfLightLightLevelReport>(instance);
        }

        /// <summary>
        /// Test the property 'Changed'
        /// </summary>
        [Fact]
        public void ChangedTest()
        {
            // TODO unit test for the property 'Changed'
        }

        /// <summary>
        /// Test the property 'LightLevel'
        /// </summary>
        [Fact]
        public void LightLevelTest()
        {
            // TODO unit test for the property 'LightLevel'
        }
    }
}
