/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing LightGetAllOfTimedEffects
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LightGetAllOfTimedEffectsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LightGetAllOfTimedEffects
        //private LightGetAllOfTimedEffects instance;

        public LightGetAllOfTimedEffectsTests()
        {
            // TODO uncomment below to create an instance of LightGetAllOfTimedEffects
            //instance = new LightGetAllOfTimedEffects();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LightGetAllOfTimedEffects
        /// </summary>
        [Fact]
        public void LightGetAllOfTimedEffectsInstanceTest()
        {
            // TODO uncomment below to test "IsType" LightGetAllOfTimedEffects
            //Assert.IsType<LightGetAllOfTimedEffects>(instance);
        }

        /// <summary>
        /// Test the property 'Effect'
        /// </summary>
        [Fact]
        public void EffectTest()
        {
            // TODO unit test for the property 'Effect'
        }

        /// <summary>
        /// Test the property 'EffectValues'
        /// </summary>
        [Fact]
        public void EffectValuesTest()
        {
            // TODO unit test for the property 'EffectValues'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'StatusValues'
        /// </summary>
        [Fact]
        public void StatusValuesTest()
        {
            // TODO unit test for the property 'StatusValues'
        }

        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
    }
}
