/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing LightGetAllOfSignaling
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LightGetAllOfSignalingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LightGetAllOfSignaling
        //private LightGetAllOfSignaling instance;

        public LightGetAllOfSignalingTests()
        {
            // TODO uncomment below to create an instance of LightGetAllOfSignaling
            //instance = new LightGetAllOfSignaling();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LightGetAllOfSignaling
        /// </summary>
        [Fact]
        public void LightGetAllOfSignalingInstanceTest()
        {
            // TODO uncomment below to test "IsType" LightGetAllOfSignaling
            //Assert.IsType<LightGetAllOfSignaling>(instance);
        }

        /// <summary>
        /// Test the property 'SignalValues'
        /// </summary>
        [Fact]
        public void SignalValuesTest()
        {
            // TODO unit test for the property 'SignalValues'
        }

        /// <summary>
        /// Test the property 'EstimatedEnd'
        /// </summary>
        [Fact]
        public void EstimatedEndTest()
        {
            // TODO unit test for the property 'EstimatedEnd'
        }

        /// <summary>
        /// Test the property 'Colors'
        /// </summary>
        [Fact]
        public void ColorsTest()
        {
            // TODO unit test for the property 'Colors'
        }
    }
}
