/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing LightPutTimedEffects
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LightPutTimedEffectsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LightPutTimedEffects
        //private LightPutTimedEffects instance;

        public LightPutTimedEffectsTests()
        {
            // TODO uncomment below to create an instance of LightPutTimedEffects
            //instance = new LightPutTimedEffects();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LightPutTimedEffects
        /// </summary>
        [Fact]
        public void LightPutTimedEffectsInstanceTest()
        {
            // TODO uncomment below to test "IsType" LightPutTimedEffects
            //Assert.IsType<LightPutTimedEffects>(instance);
        }

        /// <summary>
        /// Test the property 'Effect'
        /// </summary>
        [Fact]
        public void EffectTest()
        {
            // TODO unit test for the property 'Effect'
        }

        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }
    }
}
