/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing LightPut
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LightPutTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LightPut
        //private LightPut instance;

        public LightPutTests()
        {
            // TODO uncomment below to create an instance of LightPut
            //instance = new LightPut();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LightPut
        /// </summary>
        [Fact]
        public void LightPutInstanceTest()
        {
            // TODO uncomment below to test "IsType" LightPut
            //Assert.IsType<LightPut>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'On'
        /// </summary>
        [Fact]
        public void OnTest()
        {
            // TODO unit test for the property 'On'
        }

        /// <summary>
        /// Test the property 'Dimming'
        /// </summary>
        [Fact]
        public void DimmingTest()
        {
            // TODO unit test for the property 'Dimming'
        }

        /// <summary>
        /// Test the property 'DimmingDelta'
        /// </summary>
        [Fact]
        public void DimmingDeltaTest()
        {
            // TODO unit test for the property 'DimmingDelta'
        }

        /// <summary>
        /// Test the property 'ColorTemperature'
        /// </summary>
        [Fact]
        public void ColorTemperatureTest()
        {
            // TODO unit test for the property 'ColorTemperature'
        }

        /// <summary>
        /// Test the property 'ColorTemperatureDelta'
        /// </summary>
        [Fact]
        public void ColorTemperatureDeltaTest()
        {
            // TODO unit test for the property 'ColorTemperatureDelta'
        }

        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }

        /// <summary>
        /// Test the property 'Dynamics'
        /// </summary>
        [Fact]
        public void DynamicsTest()
        {
            // TODO unit test for the property 'Dynamics'
        }

        /// <summary>
        /// Test the property 'Alert'
        /// </summary>
        [Fact]
        public void AlertTest()
        {
            // TODO unit test for the property 'Alert'
        }

        /// <summary>
        /// Test the property 'Signaling'
        /// </summary>
        [Fact]
        public void SignalingTest()
        {
            // TODO unit test for the property 'Signaling'
        }

        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }

        /// <summary>
        /// Test the property 'Gradient'
        /// </summary>
        [Fact]
        public void GradientTest()
        {
            // TODO unit test for the property 'Gradient'
        }

        /// <summary>
        /// Test the property 'Effects'
        /// </summary>
        [Fact]
        public void EffectsTest()
        {
            // TODO unit test for the property 'Effects'
        }

        /// <summary>
        /// Test the property 'TimedEffects'
        /// </summary>
        [Fact]
        public void TimedEffectsTest()
        {
            // TODO unit test for the property 'TimedEffects'
        }

        /// <summary>
        /// Test the property 'Powerup'
        /// </summary>
        [Fact]
        public void PowerupTest()
        {
            // TODO unit test for the property 'Powerup'
        }
    }
}
