/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing LightGetAllOfPowerupDimmingColor
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LightGetAllOfPowerupDimmingColorTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LightGetAllOfPowerupDimmingColor
        //private LightGetAllOfPowerupDimmingColor instance;

        public LightGetAllOfPowerupDimmingColorTests()
        {
            // TODO uncomment below to create an instance of LightGetAllOfPowerupDimmingColor
            //instance = new LightGetAllOfPowerupDimmingColor();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LightGetAllOfPowerupDimmingColor
        /// </summary>
        [Fact]
        public void LightGetAllOfPowerupDimmingColorInstanceTest()
        {
            // TODO uncomment below to test "IsType" LightGetAllOfPowerupDimmingColor
            //Assert.IsType<LightGetAllOfPowerupDimmingColor>(instance);
        }

        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }

        /// <summary>
        /// Test the property 'ColorTemperature'
        /// </summary>
        [Fact]
        public void ColorTemperatureTest()
        {
            // TODO unit test for the property 'ColorTemperature'
        }
    }
}
