/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing LightGetAllOfPowerupOn
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LightGetAllOfPowerupOnTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LightGetAllOfPowerupOn
        //private LightGetAllOfPowerupOn instance;

        public LightGetAllOfPowerupOnTests()
        {
            // TODO uncomment below to create an instance of LightGetAllOfPowerupOn
            //instance = new LightGetAllOfPowerupOn();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LightGetAllOfPowerupOn
        /// </summary>
        [Fact]
        public void LightGetAllOfPowerupOnInstanceTest()
        {
            // TODO uncomment below to test "IsType" LightGetAllOfPowerupOn
            //Assert.IsType<LightGetAllOfPowerupOn>(instance);
        }

        /// <summary>
        /// Test the property 'Mode'
        /// </summary>
        [Fact]
        public void ModeTest()
        {
            // TODO unit test for the property 'Mode'
        }

        /// <summary>
        /// Test the property 'On'
        /// </summary>
        [Fact]
        public void OnTest()
        {
            // TODO unit test for the property 'On'
        }
    }
}
