/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing MotionGetAllOfSensitivity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MotionGetAllOfSensitivityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MotionGetAllOfSensitivity
        //private MotionGetAllOfSensitivity instance;

        public MotionGetAllOfSensitivityTests()
        {
            // TODO uncomment below to create an instance of MotionGetAllOfSensitivity
            //instance = new MotionGetAllOfSensitivity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MotionGetAllOfSensitivity
        /// </summary>
        [Fact]
        public void MotionGetAllOfSensitivityInstanceTest()
        {
            // TODO uncomment below to test "IsType" MotionGetAllOfSensitivity
            //Assert.IsType<MotionGetAllOfSensitivity>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Sensitivity'
        /// </summary>
        [Fact]
        public void SensitivityTest()
        {
            // TODO unit test for the property 'Sensitivity'
        }

        /// <summary>
        /// Test the property 'SensitivityMax'
        /// </summary>
        [Fact]
        public void SensitivityMaxTest()
        {
            // TODO unit test for the property 'SensitivityMax'
        }
    }
}
