/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing MotionGet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MotionGetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MotionGet
        //private MotionGet instance;

        public MotionGetTests()
        {
            // TODO uncomment below to create an instance of MotionGet
            //instance = new MotionGet();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MotionGet
        /// </summary>
        [Fact]
        public void MotionGetInstanceTest()
        {
            // TODO uncomment below to test "IsType" MotionGet
            //Assert.IsType<MotionGet>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'IdV1'
        /// </summary>
        [Fact]
        public void IdV1Test()
        {
            // TODO unit test for the property 'IdV1'
        }

        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Motion'
        /// </summary>
        [Fact]
        public void MotionTest()
        {
            // TODO unit test for the property 'Motion'
        }

        /// <summary>
        /// Test the property 'Sensitivity'
        /// </summary>
        [Fact]
        public void SensitivityTest()
        {
            // TODO unit test for the property 'Sensitivity'
        }
    }
}
