/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing ProductData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductData
        //private ProductData instance;

        public ProductDataTests()
        {
            // TODO uncomment below to create an instance of ProductData
            //instance = new ProductData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductData
        /// </summary>
        [Fact]
        public void ProductDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductData
            //Assert.IsType<ProductData>(instance);
        }

        /// <summary>
        /// Test the property 'ModelId'
        /// </summary>
        [Fact]
        public void ModelIdTest()
        {
            // TODO unit test for the property 'ModelId'
        }

        /// <summary>
        /// Test the property 'ManufacturerName'
        /// </summary>
        [Fact]
        public void ManufacturerNameTest()
        {
            // TODO unit test for the property 'ManufacturerName'
        }

        /// <summary>
        /// Test the property 'ProductName'
        /// </summary>
        [Fact]
        public void ProductNameTest()
        {
            // TODO unit test for the property 'ProductName'
        }

        /// <summary>
        /// Test the property 'ProductArchetype'
        /// </summary>
        [Fact]
        public void ProductArchetypeTest()
        {
            // TODO unit test for the property 'ProductArchetype'
        }

        /// <summary>
        /// Test the property 'Certified'
        /// </summary>
        [Fact]
        public void CertifiedTest()
        {
            // TODO unit test for the property 'Certified'
        }

        /// <summary>
        /// Test the property 'SoftwareVersion'
        /// </summary>
        [Fact]
        public void SoftwareVersionTest()
        {
            // TODO unit test for the property 'SoftwareVersion'
        }

        /// <summary>
        /// Test the property 'HardwarePlatformType'
        /// </summary>
        [Fact]
        public void HardwarePlatformTypeTest()
        {
            // TODO unit test for the property 'HardwarePlatformType'
        }
    }
}
