/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing RoomGet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RoomGetTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RoomGet
        //private RoomGet instance;

        public RoomGetTests()
        {
            // TODO uncomment below to create an instance of RoomGet
            //instance = new RoomGet();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RoomGet
        /// </summary>
        [Fact]
        public void RoomGetInstanceTest()
        {
            // TODO uncomment below to test "IsType" RoomGet
            //Assert.IsType<RoomGet>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'IdV1'
        /// </summary>
        [Fact]
        public void IdV1Test()
        {
            // TODO unit test for the property 'IdV1'
        }

        /// <summary>
        /// Test the property 'Children'
        /// </summary>
        [Fact]
        public void ChildrenTest()
        {
            // TODO unit test for the property 'Children'
        }

        /// <summary>
        /// Test the property 'Services'
        /// </summary>
        [Fact]
        public void ServicesTest()
        {
            // TODO unit test for the property 'Services'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
