/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing RoomGetAllOfMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RoomGetAllOfMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RoomGetAllOfMetadata
        //private RoomGetAllOfMetadata instance;

        public RoomGetAllOfMetadataTests()
        {
            // TODO uncomment below to create an instance of RoomGetAllOfMetadata
            //instance = new RoomGetAllOfMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RoomGetAllOfMetadata
        /// </summary>
        [Fact]
        public void RoomGetAllOfMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" RoomGetAllOfMetadata
            //Assert.IsType<RoomGetAllOfMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Archetype'
        /// </summary>
        [Fact]
        public void ArchetypeTest()
        {
            // TODO unit test for the property 'Archetype'
        }
    }
}
