/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing ScenePost
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ScenePostTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ScenePost
        //private ScenePost instance;

        public ScenePostTests()
        {
            // TODO uncomment below to create an instance of ScenePost
            //instance = new ScenePost();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ScenePost
        /// </summary>
        [Fact]
        public void ScenePostInstanceTest()
        {
            // TODO uncomment below to test "IsType" ScenePost
            //Assert.IsType<ScenePost>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Fact]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Fact]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }

        /// <summary>
        /// Test the property 'Palette'
        /// </summary>
        [Fact]
        public void PaletteTest()
        {
            // TODO unit test for the property 'Palette'
        }

        /// <summary>
        /// Test the property 'Speed'
        /// </summary>
        [Fact]
        public void SpeedTest()
        {
            // TODO unit test for the property 'Speed'
        }

        /// <summary>
        /// Test the property 'AutoDynamic'
        /// </summary>
        [Fact]
        public void AutoDynamicTest()
        {
            // TODO unit test for the property 'AutoDynamic'
        }
    }
}
