/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing Signaling
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SignalingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Signaling
        //private Signaling instance;

        public SignalingTests()
        {
            // TODO uncomment below to create an instance of Signaling
            //instance = new Signaling();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Signaling
        /// </summary>
        [Fact]
        public void SignalingInstanceTest()
        {
            // TODO uncomment below to test "IsType" Signaling
            //Assert.IsType<Signaling>(instance);
        }

        /// <summary>
        /// Test the property 'Signal'
        /// </summary>
        [Fact]
        public void SignalTest()
        {
            // TODO unit test for the property 'Signal'
        }

        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }
    }
}
