/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using clipapisdk.Model;
using clipapisdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace clipapisdk.Test.Model
{
    /// <summary>
    ///  Class for testing TemperatureGetAllOfTemperature
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemperatureGetAllOfTemperatureTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemperatureGetAllOfTemperature
        //private TemperatureGetAllOfTemperature instance;

        public TemperatureGetAllOfTemperatureTests()
        {
            // TODO uncomment below to create an instance of TemperatureGetAllOfTemperature
            //instance = new TemperatureGetAllOfTemperature();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemperatureGetAllOfTemperature
        /// </summary>
        [Fact]
        public void TemperatureGetAllOfTemperatureInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemperatureGetAllOfTemperature
            //Assert.IsType<TemperatureGetAllOfTemperature>(instance);
        }

        /// <summary>
        /// Test the property 'Temperature'
        /// </summary>
        [Fact]
        public void TemperatureTest()
        {
            // TODO unit test for the property 'Temperature'
        }

        /// <summary>
        /// Test the property 'TemperatureValid'
        /// </summary>
        [Fact]
        public void TemperatureValidTest()
        {
            // TODO unit test for the property 'TemperatureValid'
        }

        /// <summary>
        /// Test the property 'TemperatureReport'
        /// </summary>
        [Fact]
        public void TemperatureReportTest()
        {
            // TODO unit test for the property 'TemperatureReport'
        }
    }
}
