/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using clipapisdk.Client;
using clipapisdk.Model;

namespace clipapisdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBridgeApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get bridge
        /// </summary>
        /// <remarks>
        /// Get details of a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetBridges200Response</returns>
        GetBridges200Response GetBridge(string bridgeId, int operationIndex = 0);

        /// <summary>
        /// Get bridge
        /// </summary>
        /// <remarks>
        /// Get details of a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetBridges200Response</returns>
        ApiResponse<GetBridges200Response> GetBridgeWithHttpInfo(string bridgeId, int operationIndex = 0);
        /// <summary>
        /// List bridges
        /// </summary>
        /// <remarks>
        /// List all available bridges
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetBridges200Response</returns>
        GetBridges200Response GetBridges(int operationIndex = 0);

        /// <summary>
        /// List bridges
        /// </summary>
        /// <remarks>
        /// List all available bridges
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetBridges200Response</returns>
        ApiResponse<GetBridges200Response> GetBridgesWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// Update bridge
        /// </summary>
        /// <remarks>
        /// Update a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="bridgePut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UpdateDevice200Response</returns>
        UpdateDevice200Response UpdateBridge(string bridgeId, BridgePut? bridgePut = default(BridgePut?), int operationIndex = 0);

        /// <summary>
        /// Update bridge
        /// </summary>
        /// <remarks>
        /// Update a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="bridgePut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UpdateDevice200Response</returns>
        ApiResponse<UpdateDevice200Response> UpdateBridgeWithHttpInfo(string bridgeId, BridgePut? bridgePut = default(BridgePut?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBridgeApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get bridge
        /// </summary>
        /// <remarks>
        /// Get details of a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetBridges200Response</returns>
        System.Threading.Tasks.Task<GetBridges200Response> GetBridgeAsync(string bridgeId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get bridge
        /// </summary>
        /// <remarks>
        /// Get details of a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetBridges200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetBridges200Response>> GetBridgeWithHttpInfoAsync(string bridgeId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List bridges
        /// </summary>
        /// <remarks>
        /// List all available bridges
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetBridges200Response</returns>
        System.Threading.Tasks.Task<GetBridges200Response> GetBridgesAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List bridges
        /// </summary>
        /// <remarks>
        /// List all available bridges
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetBridges200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetBridges200Response>> GetBridgesWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update bridge
        /// </summary>
        /// <remarks>
        /// Update a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="bridgePut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateDevice200Response</returns>
        System.Threading.Tasks.Task<UpdateDevice200Response> UpdateBridgeAsync(string bridgeId, BridgePut? bridgePut = default(BridgePut?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Update bridge
        /// </summary>
        /// <remarks>
        /// Update a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="bridgePut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateDevice200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<UpdateDevice200Response>> UpdateBridgeWithHttpInfoAsync(string bridgeId, BridgePut? bridgePut = default(BridgePut?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBridgeApi : IBridgeApiSync, IBridgeApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class BridgeApi : IBridgeApi
    {
        private clipapisdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="BridgeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BridgeApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BridgeApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BridgeApi(string basePath)
        {
            this.Configuration = clipapisdk.Client.Configuration.MergeConfigurations(
                clipapisdk.Client.GlobalConfiguration.Instance,
                new clipapisdk.Client.Configuration { BasePath = basePath }
            );
            this.Client = new clipapisdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new clipapisdk.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = clipapisdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BridgeApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public BridgeApi(clipapisdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = clipapisdk.Client.Configuration.MergeConfigurations(
                clipapisdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new clipapisdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new clipapisdk.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = clipapisdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BridgeApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public BridgeApi(clipapisdk.Client.ISynchronousClient client, clipapisdk.Client.IAsynchronousClient asyncClient, clipapisdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = clipapisdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public clipapisdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public clipapisdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public clipapisdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public clipapisdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get bridge Get details of a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetBridges200Response</returns>
        public GetBridges200Response GetBridge(string bridgeId, int operationIndex = 0)
        {
            clipapisdk.Client.ApiResponse<GetBridges200Response> localVarResponse = GetBridgeWithHttpInfo(bridgeId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get bridge Get details of a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetBridges200Response</returns>
        public clipapisdk.Client.ApiResponse<GetBridges200Response> GetBridgeWithHttpInfo(string bridgeId, int operationIndex = 0)
        {
            // verify the required parameter 'bridgeId' is set
            if (bridgeId == null)
            {
                throw new clipapisdk.Client.ApiException(400, "Missing required parameter 'bridgeId' when calling BridgeApi->GetBridge");
            }

            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("bridgeId", clipapisdk.Client.ClientUtils.ParameterToString(bridgeId)); // path parameter

            localVarRequestOptions.Operation = "BridgeApi.GetBridge";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetBridges200Response>("/clip/v2/resource/bridge/{bridgeId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetBridge", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get bridge Get details of a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetBridges200Response</returns>
        public async System.Threading.Tasks.Task<GetBridges200Response> GetBridgeAsync(string bridgeId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            clipapisdk.Client.ApiResponse<GetBridges200Response> localVarResponse = await GetBridgeWithHttpInfoAsync(bridgeId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get bridge Get details of a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetBridges200Response)</returns>
        public async System.Threading.Tasks.Task<clipapisdk.Client.ApiResponse<GetBridges200Response>> GetBridgeWithHttpInfoAsync(string bridgeId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'bridgeId' is set
            if (bridgeId == null)
            {
                throw new clipapisdk.Client.ApiException(400, "Missing required parameter 'bridgeId' when calling BridgeApi->GetBridge");
            }


            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("bridgeId", clipapisdk.Client.ClientUtils.ParameterToString(bridgeId)); // path parameter

            localVarRequestOptions.Operation = "BridgeApi.GetBridge";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetBridges200Response>("/clip/v2/resource/bridge/{bridgeId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetBridge", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List bridges List all available bridges
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetBridges200Response</returns>
        public GetBridges200Response GetBridges(int operationIndex = 0)
        {
            clipapisdk.Client.ApiResponse<GetBridges200Response> localVarResponse = GetBridgesWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List bridges List all available bridges
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetBridges200Response</returns>
        public clipapisdk.Client.ApiResponse<GetBridges200Response> GetBridgesWithHttpInfo(int operationIndex = 0)
        {
            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "BridgeApi.GetBridges";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetBridges200Response>("/clip/v2/resource/bridge", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetBridges", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List bridges List all available bridges
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetBridges200Response</returns>
        public async System.Threading.Tasks.Task<GetBridges200Response> GetBridgesAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            clipapisdk.Client.ApiResponse<GetBridges200Response> localVarResponse = await GetBridgesWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List bridges List all available bridges
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetBridges200Response)</returns>
        public async System.Threading.Tasks.Task<clipapisdk.Client.ApiResponse<GetBridges200Response>> GetBridgesWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "BridgeApi.GetBridges";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetBridges200Response>("/clip/v2/resource/bridge", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetBridges", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update bridge Update a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="bridgePut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UpdateDevice200Response</returns>
        public UpdateDevice200Response UpdateBridge(string bridgeId, BridgePut? bridgePut = default(BridgePut?), int operationIndex = 0)
        {
            clipapisdk.Client.ApiResponse<UpdateDevice200Response> localVarResponse = UpdateBridgeWithHttpInfo(bridgeId, bridgePut);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update bridge Update a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="bridgePut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UpdateDevice200Response</returns>
        public clipapisdk.Client.ApiResponse<UpdateDevice200Response> UpdateBridgeWithHttpInfo(string bridgeId, BridgePut? bridgePut = default(BridgePut?), int operationIndex = 0)
        {
            // verify the required parameter 'bridgeId' is set
            if (bridgeId == null)
            {
                throw new clipapisdk.Client.ApiException(400, "Missing required parameter 'bridgeId' when calling BridgeApi->UpdateBridge");
            }

            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("bridgeId", clipapisdk.Client.ClientUtils.ParameterToString(bridgeId)); // path parameter
            localVarRequestOptions.Data = bridgePut;

            localVarRequestOptions.Operation = "BridgeApi.UpdateBridge";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<UpdateDevice200Response>("/clip/v2/resource/bridge/{bridgeId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateBridge", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update bridge Update a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="bridgePut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateDevice200Response</returns>
        public async System.Threading.Tasks.Task<UpdateDevice200Response> UpdateBridgeAsync(string bridgeId, BridgePut? bridgePut = default(BridgePut?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            clipapisdk.Client.ApiResponse<UpdateDevice200Response> localVarResponse = await UpdateBridgeWithHttpInfoAsync(bridgeId, bridgePut, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update bridge Update a single bridge from its given &#x60;{bridgeId}&#x60;.
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="bridgeId">ID of the bridge</param>
        /// <param name="bridgePut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateDevice200Response)</returns>
        public async System.Threading.Tasks.Task<clipapisdk.Client.ApiResponse<UpdateDevice200Response>> UpdateBridgeWithHttpInfoAsync(string bridgeId, BridgePut? bridgePut = default(BridgePut?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'bridgeId' is set
            if (bridgeId == null)
            {
                throw new clipapisdk.Client.ApiException(400, "Missing required parameter 'bridgeId' when calling BridgeApi->UpdateBridge");
            }


            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("bridgeId", clipapisdk.Client.ClientUtils.ParameterToString(bridgeId)); // path parameter
            localVarRequestOptions.Data = bridgePut;

            localVarRequestOptions.Operation = "BridgeApi.UpdateBridge";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PutAsync<UpdateDevice200Response>("/clip/v2/resource/bridge/{bridgeId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateBridge", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
