/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using clipapisdk.Client;
using clipapisdk.Model;

namespace clipapisdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IResourceApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// List resources
        /// </summary>
        /// <remarks>
        /// API to retrieve all API resources
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetResources200Response</returns>
        GetResources200Response GetResources(int operationIndex = 0);

        /// <summary>
        /// List resources
        /// </summary>
        /// <remarks>
        /// API to retrieve all API resources
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetResources200Response</returns>
        ApiResponse<GetResources200Response> GetResourcesWithHttpInfo(int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IResourceApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// List resources
        /// </summary>
        /// <remarks>
        /// API to retrieve all API resources
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetResources200Response</returns>
        System.Threading.Tasks.Task<GetResources200Response> GetResourcesAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List resources
        /// </summary>
        /// <remarks>
        /// API to retrieve all API resources
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetResources200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetResources200Response>> GetResourcesWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IResourceApi : IResourceApiSync, IResourceApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ResourceApi : IResourceApi
    {
        private clipapisdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ResourceApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ResourceApi(string basePath)
        {
            this.Configuration = clipapisdk.Client.Configuration.MergeConfigurations(
                clipapisdk.Client.GlobalConfiguration.Instance,
                new clipapisdk.Client.Configuration { BasePath = basePath }
            );
            this.Client = new clipapisdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new clipapisdk.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = clipapisdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ResourceApi(clipapisdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = clipapisdk.Client.Configuration.MergeConfigurations(
                clipapisdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new clipapisdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new clipapisdk.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = clipapisdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResourceApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ResourceApi(clipapisdk.Client.ISynchronousClient client, clipapisdk.Client.IAsynchronousClient asyncClient, clipapisdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = clipapisdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public clipapisdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public clipapisdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public clipapisdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public clipapisdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// List resources API to retrieve all API resources
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetResources200Response</returns>
        public GetResources200Response GetResources(int operationIndex = 0)
        {
            clipapisdk.Client.ApiResponse<GetResources200Response> localVarResponse = GetResourcesWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List resources API to retrieve all API resources
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetResources200Response</returns>
        public clipapisdk.Client.ApiResponse<GetResources200Response> GetResourcesWithHttpInfo(int operationIndex = 0)
        {
            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ResourceApi.GetResources";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetResources200Response>("/clip/v2/resource", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetResources", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List resources API to retrieve all API resources
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetResources200Response</returns>
        public async System.Threading.Tasks.Task<GetResources200Response> GetResourcesAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            clipapisdk.Client.ApiResponse<GetResources200Response> localVarResponse = await GetResourcesWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List resources API to retrieve all API resources
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetResources200Response)</returns>
        public async System.Threading.Tasks.Task<clipapisdk.Client.ApiResponse<GetResources200Response>> GetResourcesWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ResourceApi.GetResources";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetResources200Response>("/clip/v2/resource", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetResources", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
