/*
 * Hue CLIP API
 *
 * See [openhue/openhue-api](https://github.com/openhue/openhue-api)
 *
 * The version of the OpenAPI document: v2
 * Contact: contact@openhue.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using clipapisdk.Client;
using clipapisdk.Model;

namespace clipapisdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IZoneApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create zone
        /// </summary>
        /// <remarks>
        /// Create a new zone
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UpdateDevice200Response</returns>
        UpdateDevice200Response CreateZone(RoomPut? roomPut = default(RoomPut?), int operationIndex = 0);

        /// <summary>
        /// Create zone
        /// </summary>
        /// <remarks>
        /// Create a new zone
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UpdateDevice200Response</returns>
        ApiResponse<UpdateDevice200Response> CreateZoneWithHttpInfo(RoomPut? roomPut = default(RoomPut?), int operationIndex = 0);
        /// <summary>
        /// Delete Zone
        /// </summary>
        /// <remarks>
        /// Delete a single Zone from its given &#x60;{zoneId}&#x60;
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UpdateDevice200Response</returns>
        UpdateDevice200Response DeleteZone(string zoneId, int operationIndex = 0);

        /// <summary>
        /// Delete Zone
        /// </summary>
        /// <remarks>
        /// Delete a single Zone from its given &#x60;{zoneId}&#x60;
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UpdateDevice200Response</returns>
        ApiResponse<UpdateDevice200Response> DeleteZoneWithHttpInfo(string zoneId, int operationIndex = 0);
        /// <summary>
        /// Get Zone.
        /// </summary>
        /// <remarks>
        /// Get details of a single Zone from its given &#x60;{zoneId}&#x60;
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetRooms200Response</returns>
        GetRooms200Response GetZone(string zoneId, int operationIndex = 0);

        /// <summary>
        /// Get Zone.
        /// </summary>
        /// <remarks>
        /// Get details of a single Zone from its given &#x60;{zoneId}&#x60;
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetRooms200Response</returns>
        ApiResponse<GetRooms200Response> GetZoneWithHttpInfo(string zoneId, int operationIndex = 0);
        /// <summary>
        /// List zones
        /// </summary>
        /// <remarks>
        /// List all available zones
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetRooms200Response</returns>
        GetRooms200Response GetZones(int operationIndex = 0);

        /// <summary>
        /// List zones
        /// </summary>
        /// <remarks>
        /// List all available zones
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetRooms200Response</returns>
        ApiResponse<GetRooms200Response> GetZonesWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// Update Zone
        /// </summary>
        /// <remarks>
        /// Update a single Zone from its given &#x60;{zoneId}&#x60;
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UpdateDevice200Response</returns>
        UpdateDevice200Response UpdateZone(string zoneId, RoomPut? roomPut = default(RoomPut?), int operationIndex = 0);

        /// <summary>
        /// Update Zone
        /// </summary>
        /// <remarks>
        /// Update a single Zone from its given &#x60;{zoneId}&#x60;
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UpdateDevice200Response</returns>
        ApiResponse<UpdateDevice200Response> UpdateZoneWithHttpInfo(string zoneId, RoomPut? roomPut = default(RoomPut?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IZoneApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create zone
        /// </summary>
        /// <remarks>
        /// Create a new zone
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateDevice200Response</returns>
        System.Threading.Tasks.Task<UpdateDevice200Response> CreateZoneAsync(RoomPut? roomPut = default(RoomPut?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create zone
        /// </summary>
        /// <remarks>
        /// Create a new zone
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateDevice200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<UpdateDevice200Response>> CreateZoneWithHttpInfoAsync(RoomPut? roomPut = default(RoomPut?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete Zone
        /// </summary>
        /// <remarks>
        /// Delete a single Zone from its given &#x60;{zoneId}&#x60;
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateDevice200Response</returns>
        System.Threading.Tasks.Task<UpdateDevice200Response> DeleteZoneAsync(string zoneId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete Zone
        /// </summary>
        /// <remarks>
        /// Delete a single Zone from its given &#x60;{zoneId}&#x60;
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateDevice200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<UpdateDevice200Response>> DeleteZoneWithHttpInfoAsync(string zoneId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get Zone.
        /// </summary>
        /// <remarks>
        /// Get details of a single Zone from its given &#x60;{zoneId}&#x60;
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetRooms200Response</returns>
        System.Threading.Tasks.Task<GetRooms200Response> GetZoneAsync(string zoneId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get Zone.
        /// </summary>
        /// <remarks>
        /// Get details of a single Zone from its given &#x60;{zoneId}&#x60;
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetRooms200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetRooms200Response>> GetZoneWithHttpInfoAsync(string zoneId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List zones
        /// </summary>
        /// <remarks>
        /// List all available zones
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetRooms200Response</returns>
        System.Threading.Tasks.Task<GetRooms200Response> GetZonesAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List zones
        /// </summary>
        /// <remarks>
        /// List all available zones
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetRooms200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<GetRooms200Response>> GetZonesWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update Zone
        /// </summary>
        /// <remarks>
        /// Update a single Zone from its given &#x60;{zoneId}&#x60;
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateDevice200Response</returns>
        System.Threading.Tasks.Task<UpdateDevice200Response> UpdateZoneAsync(string zoneId, RoomPut? roomPut = default(RoomPut?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Update Zone
        /// </summary>
        /// <remarks>
        /// Update a single Zone from its given &#x60;{zoneId}&#x60;
        /// </remarks>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateDevice200Response)</returns>
        System.Threading.Tasks.Task<ApiResponse<UpdateDevice200Response>> UpdateZoneWithHttpInfoAsync(string zoneId, RoomPut? roomPut = default(RoomPut?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IZoneApi : IZoneApiSync, IZoneApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ZoneApi : IZoneApi
    {
        private clipapisdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ZoneApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ZoneApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ZoneApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ZoneApi(string basePath)
        {
            this.Configuration = clipapisdk.Client.Configuration.MergeConfigurations(
                clipapisdk.Client.GlobalConfiguration.Instance,
                new clipapisdk.Client.Configuration { BasePath = basePath }
            );
            this.Client = new clipapisdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new clipapisdk.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = clipapisdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ZoneApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ZoneApi(clipapisdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = clipapisdk.Client.Configuration.MergeConfigurations(
                clipapisdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new clipapisdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new clipapisdk.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = clipapisdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ZoneApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public ZoneApi(clipapisdk.Client.ISynchronousClient client, clipapisdk.Client.IAsynchronousClient asyncClient, clipapisdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = clipapisdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public clipapisdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public clipapisdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public clipapisdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public clipapisdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create zone Create a new zone
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UpdateDevice200Response</returns>
        public UpdateDevice200Response CreateZone(RoomPut? roomPut = default(RoomPut?), int operationIndex = 0)
        {
            clipapisdk.Client.ApiResponse<UpdateDevice200Response> localVarResponse = CreateZoneWithHttpInfo(roomPut);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create zone Create a new zone
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UpdateDevice200Response</returns>
        public clipapisdk.Client.ApiResponse<UpdateDevice200Response> CreateZoneWithHttpInfo(RoomPut? roomPut = default(RoomPut?), int operationIndex = 0)
        {
            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = roomPut;

            localVarRequestOptions.Operation = "ZoneApi.CreateZone";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<UpdateDevice200Response>("/clip/v2/resource/zone", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateZone", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create zone Create a new zone
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateDevice200Response</returns>
        public async System.Threading.Tasks.Task<UpdateDevice200Response> CreateZoneAsync(RoomPut? roomPut = default(RoomPut?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            clipapisdk.Client.ApiResponse<UpdateDevice200Response> localVarResponse = await CreateZoneWithHttpInfoAsync(roomPut, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create zone Create a new zone
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateDevice200Response)</returns>
        public async System.Threading.Tasks.Task<clipapisdk.Client.ApiResponse<UpdateDevice200Response>> CreateZoneWithHttpInfoAsync(RoomPut? roomPut = default(RoomPut?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = roomPut;

            localVarRequestOptions.Operation = "ZoneApi.CreateZone";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<UpdateDevice200Response>("/clip/v2/resource/zone", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateZone", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Zone Delete a single Zone from its given &#x60;{zoneId}&#x60;
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UpdateDevice200Response</returns>
        public UpdateDevice200Response DeleteZone(string zoneId, int operationIndex = 0)
        {
            clipapisdk.Client.ApiResponse<UpdateDevice200Response> localVarResponse = DeleteZoneWithHttpInfo(zoneId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Zone Delete a single Zone from its given &#x60;{zoneId}&#x60;
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UpdateDevice200Response</returns>
        public clipapisdk.Client.ApiResponse<UpdateDevice200Response> DeleteZoneWithHttpInfo(string zoneId, int operationIndex = 0)
        {
            // verify the required parameter 'zoneId' is set
            if (zoneId == null)
            {
                throw new clipapisdk.Client.ApiException(400, "Missing required parameter 'zoneId' when calling ZoneApi->DeleteZone");
            }

            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("zoneId", clipapisdk.Client.ClientUtils.ParameterToString(zoneId)); // path parameter

            localVarRequestOptions.Operation = "ZoneApi.DeleteZone";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<UpdateDevice200Response>("/clip/v2/resource/zone/{zoneId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteZone", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Zone Delete a single Zone from its given &#x60;{zoneId}&#x60;
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateDevice200Response</returns>
        public async System.Threading.Tasks.Task<UpdateDevice200Response> DeleteZoneAsync(string zoneId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            clipapisdk.Client.ApiResponse<UpdateDevice200Response> localVarResponse = await DeleteZoneWithHttpInfoAsync(zoneId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Zone Delete a single Zone from its given &#x60;{zoneId}&#x60;
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateDevice200Response)</returns>
        public async System.Threading.Tasks.Task<clipapisdk.Client.ApiResponse<UpdateDevice200Response>> DeleteZoneWithHttpInfoAsync(string zoneId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'zoneId' is set
            if (zoneId == null)
            {
                throw new clipapisdk.Client.ApiException(400, "Missing required parameter 'zoneId' when calling ZoneApi->DeleteZone");
            }


            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("zoneId", clipapisdk.Client.ClientUtils.ParameterToString(zoneId)); // path parameter

            localVarRequestOptions.Operation = "ZoneApi.DeleteZone";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<UpdateDevice200Response>("/clip/v2/resource/zone/{zoneId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteZone", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Zone. Get details of a single Zone from its given &#x60;{zoneId}&#x60;
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetRooms200Response</returns>
        public GetRooms200Response GetZone(string zoneId, int operationIndex = 0)
        {
            clipapisdk.Client.ApiResponse<GetRooms200Response> localVarResponse = GetZoneWithHttpInfo(zoneId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Zone. Get details of a single Zone from its given &#x60;{zoneId}&#x60;
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetRooms200Response</returns>
        public clipapisdk.Client.ApiResponse<GetRooms200Response> GetZoneWithHttpInfo(string zoneId, int operationIndex = 0)
        {
            // verify the required parameter 'zoneId' is set
            if (zoneId == null)
            {
                throw new clipapisdk.Client.ApiException(400, "Missing required parameter 'zoneId' when calling ZoneApi->GetZone");
            }

            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("zoneId", clipapisdk.Client.ClientUtils.ParameterToString(zoneId)); // path parameter

            localVarRequestOptions.Operation = "ZoneApi.GetZone";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetRooms200Response>("/clip/v2/resource/zone/{zoneId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetZone", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Zone. Get details of a single Zone from its given &#x60;{zoneId}&#x60;
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetRooms200Response</returns>
        public async System.Threading.Tasks.Task<GetRooms200Response> GetZoneAsync(string zoneId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            clipapisdk.Client.ApiResponse<GetRooms200Response> localVarResponse = await GetZoneWithHttpInfoAsync(zoneId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Zone. Get details of a single Zone from its given &#x60;{zoneId}&#x60;
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetRooms200Response)</returns>
        public async System.Threading.Tasks.Task<clipapisdk.Client.ApiResponse<GetRooms200Response>> GetZoneWithHttpInfoAsync(string zoneId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'zoneId' is set
            if (zoneId == null)
            {
                throw new clipapisdk.Client.ApiException(400, "Missing required parameter 'zoneId' when calling ZoneApi->GetZone");
            }


            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("zoneId", clipapisdk.Client.ClientUtils.ParameterToString(zoneId)); // path parameter

            localVarRequestOptions.Operation = "ZoneApi.GetZone";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetRooms200Response>("/clip/v2/resource/zone/{zoneId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetZone", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List zones List all available zones
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>GetRooms200Response</returns>
        public GetRooms200Response GetZones(int operationIndex = 0)
        {
            clipapisdk.Client.ApiResponse<GetRooms200Response> localVarResponse = GetZonesWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List zones List all available zones
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of GetRooms200Response</returns>
        public clipapisdk.Client.ApiResponse<GetRooms200Response> GetZonesWithHttpInfo(int operationIndex = 0)
        {
            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ZoneApi.GetZones";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<GetRooms200Response>("/clip/v2/resource/zone", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetZones", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List zones List all available zones
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of GetRooms200Response</returns>
        public async System.Threading.Tasks.Task<GetRooms200Response> GetZonesAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            clipapisdk.Client.ApiResponse<GetRooms200Response> localVarResponse = await GetZonesWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List zones List all available zones
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (GetRooms200Response)</returns>
        public async System.Threading.Tasks.Task<clipapisdk.Client.ApiResponse<GetRooms200Response>> GetZonesWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "ZoneApi.GetZones";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<GetRooms200Response>("/clip/v2/resource/zone", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetZones", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Zone Update a single Zone from its given &#x60;{zoneId}&#x60;
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>UpdateDevice200Response</returns>
        public UpdateDevice200Response UpdateZone(string zoneId, RoomPut? roomPut = default(RoomPut?), int operationIndex = 0)
        {
            clipapisdk.Client.ApiResponse<UpdateDevice200Response> localVarResponse = UpdateZoneWithHttpInfo(zoneId, roomPut);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Zone Update a single Zone from its given &#x60;{zoneId}&#x60;
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of UpdateDevice200Response</returns>
        public clipapisdk.Client.ApiResponse<UpdateDevice200Response> UpdateZoneWithHttpInfo(string zoneId, RoomPut? roomPut = default(RoomPut?), int operationIndex = 0)
        {
            // verify the required parameter 'zoneId' is set
            if (zoneId == null)
            {
                throw new clipapisdk.Client.ApiException(400, "Missing required parameter 'zoneId' when calling ZoneApi->UpdateZone");
            }

            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("zoneId", clipapisdk.Client.ClientUtils.ParameterToString(zoneId)); // path parameter
            localVarRequestOptions.Data = roomPut;

            localVarRequestOptions.Operation = "ZoneApi.UpdateZone";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Put<UpdateDevice200Response>("/clip/v2/resource/zone/{zoneId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateZone", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Zone Update a single Zone from its given &#x60;{zoneId}&#x60;
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of UpdateDevice200Response</returns>
        public async System.Threading.Tasks.Task<UpdateDevice200Response> UpdateZoneAsync(string zoneId, RoomPut? roomPut = default(RoomPut?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            clipapisdk.Client.ApiResponse<UpdateDevice200Response> localVarResponse = await UpdateZoneWithHttpInfoAsync(zoneId, roomPut, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Zone Update a single Zone from its given &#x60;{zoneId}&#x60;
        /// </summary>
        /// <exception cref="clipapisdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="zoneId">ID of the Zone</param>
        /// <param name="roomPut"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (UpdateDevice200Response)</returns>
        public async System.Threading.Tasks.Task<clipapisdk.Client.ApiResponse<UpdateDevice200Response>> UpdateZoneWithHttpInfoAsync(string zoneId, RoomPut? roomPut = default(RoomPut?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'zoneId' is set
            if (zoneId == null)
            {
                throw new clipapisdk.Client.ApiException(400, "Missing required parameter 'zoneId' when calling ZoneApi->UpdateZone");
            }


            clipapisdk.Client.RequestOptions localVarRequestOptions = new clipapisdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = clipapisdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = clipapisdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("zoneId", clipapisdk.Client.ClientUtils.ParameterToString(zoneId)); // path parameter
            localVarRequestOptions.Data = roomPut;

            localVarRequestOptions.Operation = "ZoneApi.UpdateZone";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HueApplicationKey) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("hue-application-key")))
            {
                localVarRequestOptions.HeaderParameters.Add("hue-application-key", this.Configuration.GetApiKeyWithPrefix("hue-application-key"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PutAsync<UpdateDevice200Response>("/clip/v2/resource/zone/{zoneId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateZone", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
